# For workspace name
# The checkpoint file location to be saved: {workspace}/checkpoints/
# The log file location to be saved: {workspace}/tensorboard_logs/
workspace: ''

dataset: funsd
task: ee_el

dataset_root_path: /workspaces/hungvm5/GeoLayoutLM/preprocess/dataset/funsd_geo

pretrained_model_path: 

seed: 1
cudnn_deterministic: False
cudnn_benchmark: True

model:
  backbone: alibaba-damo/geolayoutlm-large-uncased
  head: vie
  n_classes: 7
  config_json: configs/GeoLayoutLM/GeoLayoutLM_base_model_config.json
  use_inner_id: true
  max_prob_as_father: true
  max_prob_as_father_upperbound: false

train:
  batch_size: 2
  num_samples_per_epoch: 150
  max_epochs: 100
  use_fp16: True
  accelerator: gpu
  strategy:
    type: ddp

  clip_gradient_algorithm: norm
  clip_gradient_value: 1.0
  num_workers: 0

  optimizer:
    method: adamw
    params:
      lr: 5e-5
    lr_schedule:
      method: linear
      params:
        warmup_steps: 0

  val_interval: 1  # in epochs

val:
  batch_size: 4
  num_workers: 0
  limit_val_batches: 1.0
