# For workspace name
# The checkpoint file location to be saved: {workspace}/checkpoints/
# The log file location to be saved: {workspace}/tensorboard_logs/
workspace: ''
save_weight_dir: tensorboard_logs
dataset: HANAM
dataset_root_path: data_HaNam/hanam_geo_pho
task: ee_el
img_h: 768
img_w: 768
num_class: 11
model:
  backbone: alibaba-damo/geolayoutlm-large-uncased
  config_json: configs/GeoLayoutLM/GeoLayoutLM_large_model_config.json
  model_ckpt: checkpoints/geolayoutlm_large_pretrain.pt
  head: vie
  use_inner_id: true
  max_prob_as_father: true
  max_prob_as_father_upperbound: false

train:
  batch_size: 1
  num_samples_per_epoch: 149
  max_seq_length: 256
  max_block_num: 150  # 150
  max_epochs: 150
  use_fp16: False
  accelerator: gpu
  strategy:
    type: ""

  clip_gradient_algorithm: norm
  clip_gradient_value: 1.0
  num_workers: 0

  optimizer:
    method: adamw
    params:
      lr: 2e-5
      weight_decay: 0.01
      eps: !!float 1e-8
    lr_schedule:
      method: linear
      params:
        warmup_steps: 200

  val_interval: 1  # in epochs

val:
  batch_size: 1
  num_workers: 0
  limit_val_batches: 1.0
  dump_dir: geollm/HANAM_PHO
  pretrained_best_type: linking # labeling, linking

pretrained_model_file: ~

